# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-05 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
