# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0003_auto_20170401_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default='An uploaded file', max_length=255),
        ),
    ]
