# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0004_auto_20170408_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMail', models.CharField(default='', max_length=100, verbose_name='User Email')),
                ('reason', models.CharField(default='', max_length=250, verbose_name='reason')),
                ('timeAdmitted', models.DateTimeField(default=None, verbose_name='Time Admitted')),
                ('admittedBy', models.CharField(default='', max_length=100, verbose_name='Admitted by')),
                ('timeDischarged', models.DateTimeField(default=None, verbose_name='Time Discharged')),
                ('dischargedBy', models.CharField(default='', max_length=100, verbose_name='Discharged by')),
                ('admitStatus', models.BooleanField(default=False, verbose_name='Admission Status')),
            ],
            options={
                'verbose_name': 'Admission Log entry',
                'verbose_name_plural': 'Admission Log entries',
            },
        ),
    ]
