# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-08 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0005_admissionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedInfo',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HealthApp.Patient', verbose_name='Patient')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time recorded')),
                ('heart_rate', models.IntegerField(help_text='beats per minute', verbose_name='Heart Rate')),
                ('systolic_pressure', models.IntegerField(help_text='mmHg', verbose_name='Systolic Blood Pressure')),
                ('diastolic_pressure', models.IntegerField(help_text='mmHg', verbose_name='Diastolic Blood Pressure')),
                ('body_temp', models.IntegerField(help_text='Fahrenheit', verbose_name='Body Temperature')),
                ('respiratory_rate', models.IntegerField(help_text='breaths per minute', verbose_name='Respiratory Rate')),
                ('notes', models.CharField(default='', max_length=1000, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=50, verbose_name='Drug Name')),
                ('date', models.DateField(auto_now=True, verbose_name='Date prescribed')),
                ('refills', models.IntegerField(verbose_name='Number of Refills')),
                ('notes', models.CharField(default='', max_length=1000, verbose_name='Notes')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.Doctor', verbose_name='Doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.Patient', verbose_name='Patient')),
            ],
        ),
        migrations.AddField(
            model_name='admissionlog',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Hospital', to='HealthApp.Hospital', verbose_name='Hospital'),
        ),
    ]
