# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0007_message_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, verbose_name='read at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='unread'),
        ),
    ]
