# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0009_auto_20170415_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='releaseStatus',
            field=models.BooleanField(default=False, verbose_name='Released to Patient Status'),
        ),
    ]
