# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0010_test_releasestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionlog',
            options={'verbose_name': 'Admission log entry', 'verbose_name_plural': 'Admission log entries'},
        ),
        migrations.AlterField(
            model_name='admissionlog',
            name='dischargedBy',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Discharged by'),
        ),
        migrations.AlterField(
            model_name='admissionlog',
            name='timeDischarged',
            field=models.DateTimeField(default=None, null=True, verbose_name='Time Discharged'),
        ),
    ]
