# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0012_auto_20170415_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test', to='HealthApp.Test', verbose_name='Test result'),
        ),
    ]
