# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0013_auto_20170415_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Test Date'),
        ),
        migrations.AlterField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthApp.Patient', verbose_name='Patient'),
        ),
    ]
