# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0016_auto_20170416_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='body_temp',
            field=models.IntegerField(default=0, help_text='Fahrenheit', verbose_name='Body Temperature'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='diastolic_pressure',
            field=models.IntegerField(default=0, help_text='mmHg', verbose_name='Diastolic Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='heart_rate',
            field=models.IntegerField(default=0, help_text='beats per minute', verbose_name='Heart Rate'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='respiratory_rate',
            field=models.IntegerField(default=0, help_text='breaths per minute', verbose_name='Respiratory Rate'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='systolic_pressure',
            field=models.IntegerField(default=0, help_text='mmHg', verbose_name='Systolic Blood Pressure'),
        ),
    ]
