# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0018_auto_20170417_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='e_cont_cell_phone',
            field=models.BigIntegerField(verbose_name='Emergency Contact: Cell Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='e_cont_home_phone',
            field=models.BigIntegerField(verbose_name='Emergency Contact: Home Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cell_phone',
            field=models.BigIntegerField(verbose_name='Cell Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_phone',
            field=models.BigIntegerField(verbose_name='Home Phone'),
        ),
    ]
