# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0019_auto_20170502_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='refills',
            field=models.IntegerField(default=0, verbose_name='Number of Refills'),
        ),
    ]
