from .add_appointment import AddAppointment
from .admit_patient import AdmitPatient
from .create_test_result import CreateTestForm
from .discharge_patient import DischargePatient
from .login import Login
from .register import Register
from .set_patient_hospital import SetPatientHospital
from .update_appointment import UpdateAppointment
from .update_patient import UpdatePatient
from .upload_file import UploadForm
from .send_message import SendMessage
